[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
hlskit = { path = "../hlskit-rs", features = ["zenpulse-api", "native-bindings"] }
tokio = { version = "1.43.0", features = ["full"] }
